[build]
  publish = "public"
  command = "npm install --legacy-peer-deps --force && npm run build"
[build.environment]
  NODE_VERSION = "18.0.0"
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"


