[build]
  publish = "public"
  command = "npm install --legacy-peer-deps && npm run build"
[build.environment]
  NODE_VERSION = "20.11.1"
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"


